version: '3.8'

services:
  base:
    image: fluidnc-ledscreen-base:latest
    build:
      context: .
      dockerfile: fluidnc-monitor/Dockerfile.base

  fluidnc-monitor:
    build:
      context: .
      dockerfile: fluidnc-monitor/Dockerfile
    container_name: fluidnc-monitor
    depends_on:
      - base
    volumes:
      - ./fluidnc-monitor/logs:/app/logs
      - /dev/gpiomem0:/dev/gpiomem
      - /dev/pio0:/dev/pio0
    devices:
      - /dev/gpiomem0:/dev/gpiomem
      - /dev/pio0:/dev/pio0
    restart: unless-stopped
    networks:
      - fluidnc-network

volumes:
  fluidnc_logs:
    name: fluidnc_logs

networks:
  fluidnc-network:
    driver: bridge
